create database hospital;
use hospital;
create table patient(id int,name varchar(40),age int,gender varchar(40));
select*from patient;
select gender from patient;
insert into patient values(101,'kaila',24,'male');
select name from patient;
show databases;
show tables;
describe patient;
show columns from patient;
show create table patient;
alter table patient add column phone_no int; 
alter table patient drop column phone_no;
alter table patient rename to customer;
select* from customer;
rename table customer to emp;
truncate table emp;
rename table emp to patient;
drop table patient;
set sql_safe_updates=0;
delete from patient where id= 101;
drop database hospital;
