 create database company;
 use company;
 create table employee(emp_id int,emp_name varchar(40),emp_salary int,emp_bonas int);
 insert into employee values(5,"rajakumar",35000,15000);
 select*from employee;
 select emp_salary+emp_bonas as emp_totalsalery from employee; 
 select emp_salary-emp_bonas as emp_totalsalery from employee; 
 select emp_salary*emp_bonas as emp_totalsalery from employee;
 select emp_salary+emp_bonas/2 as emp_totalsalery from employee;
--   select first_operand%second_operand remainder from employee;- 
select*from employee where emp_salary=40000;
select*from employee where emp_salary!=40000;
select*from employee where emp_id<=2;
create table bitwise(no_one int,no_two int);
insert into bitwise values(5,1);
select no_one % no_two from bitwise;
select 12+8;
select count(*) from employee;
select current_timestamp();
select current_time();
select current_date();
create table emp(em_id int,name varchar(50),job_desc varchar(60),salary int);
insert into emp values(11,"saravana","CEO",70000);
set sql_safe_updates=0;
delete from emp where job_desc="CEO";
select*from emp where name="kishore";
select*from emp where salary<70000 and job_desc="manager";
select*from emp where job_desc="client" or job_desc="fdeveloper";
select*from emp where job_desc not in("manager","CEO");
select*from emp where salary between 24000 and 30000;
select*from emp limit 2;
select*from emp where name like "_a%";
select distinct name from emp;
select*from emp order by name;
select*from emp order by salary asc;
select*from emp where job_desc="fdeveloper"order by salary;
select job_desc,count(salary)from emp group by job_desc;
select job_desc,count(em_id)from emp group by job_desc having count(em_id)>1;